name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  frontend:
    name: Build Vue frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build Vue app
        run: npx nx build weather-widget-fe --skip-nx-cache

  backend:
    name: FastAPI Backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: survey_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (FastAPI)
        run: |
          cd apps/survey-be
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run Alembic migrations
        run: |
          cd apps/survey-be
          source venv/bin/activate
          export DATABASE_URL=postgresql://postgres:postgres@postgres:5432/survey_db
          alembic upgrade head
      - name: Run FastAPI
        run: |
          cd apps/survey-be/src
          source ../venv/bin/activate
          export DATABASE_URL=postgresql://postgres:postgres@postgres:5432/survey_db
          uvicorn main:app --host 0.0.0.0 --port 8000 &
