name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  frontend:
    name: Build Vue frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/weather-widget-fe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build Vue app
        run: npx nx build weather-widget-fe

  backend:
    name: FastAPI Backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (FastAPI)
        run: |
          cd apps/fastapi-be
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run FastAPI
        run: |
          cd apps/fastapi-be
          uvicorn main:app --host 0.0.0.0 --port 8000 &
      # Aquí podrías sumar tests en el futuro
